### ISSUE TITLE
[12.0] stock_move_location_dest_constraint_tag

### ISSUE THREAD

**Issue by Zephyria77** [OCA/wms#11]
I've tried this module with various settings https://github.com/guewen/stock-logistics-warehouse/tree/wms-aggr/stock_move_location_dest_constraint_tag
Example: 
Product A 
Product B
Customer
Address Customer A (destination of Product A)(SubLocation CustomerA)
Address Customer B (destination of Product B)(SubLocation CustomerB)

SO:
Product A (putaway Rule A direct on Address Customer A)
Product B (putaway Rule B direct on Address Customer B)

Expected Result on Confirm:
2 delivery 
WH/OUT1  with destination of Product A
WH/OUT2  with destination of Product B

But it doesn't happen
Maybe I've commited some error to understand the module?
I accept advice, Sorry for my question but I don't know where to bang my head anymore

Thank you in advance

**Comment by rousseldenis** [comment]
You've tested a module which is not part yet of OCA. Please do issue in guewen repo
