### ISSUE TITLE
base_REST new API

### ISSUE THREAD

**Issue by hparfr** [OCA/wms#129]
Hi,

As @lmignon commented in the https://github.com/OCA/rest-framework/pull/71

> I would like to merge this PR in 13.0 and have it as the basis for 14.0.

I did a quick & dirty patch just to see I it installs and runs in 14.0. See the commit https://github.com/OCA/wms/commit/22dec956a4f5a08425e154db8a37c5acf11eae3e

To minimize the divergence between v13 and v14, I would like to base shopfloor v13 on base_rest new API after the merge of https://github.com/OCA/rest-framework/pull/71  

Is it ok for you ? @guewen @simahawk

**Comment by simahawk** [comment]
@hparfr good for me but then we need help w/ reviews on that PR :wink:

**Comment by simahawk** [comment]
@hparfr FYI https://github.com/OCA/wms/pull/133 https://github.com/OCA/rest-framework/pull/99

**Comment by hparfr** [comment]
base_rest is now aligned in 14.0 and 13.0
