### ISSUE TITLE
shopfloor_mobile need documentation to setup API

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/wms#134]
![shopfloor_mobile](https://user-images.githubusercontent.com/13952131/105174160-6cf5dd00-5b22-11eb-8f39-48c3ffcc27c3.png)
which are the steps to setup API key?
thanks

**Comment by simahawk** [comment]
Settings -> Technical -> Api keys (see https://github.com/OCA/server-auth/tree/13.0/auth_api_key#id1)

**Comment by andreampiovesana** [comment]
i read ..
add a new section to your configuration file according to the following convention:
[api_key_Record Name]
key=my_api_key
but
for shopfloor_mobile what i have to write for Record Name ?
my_api_key how many chars?
thanks

**Comment by simahawk** [comment]
> i read ..
> add a new section to your configuration file according to the following convention:
> [api_key_Record Name]
> key=my_api_key
> but
> for shopfloor_mobile what i have to write for Record Name ?
> my_api_key how many chars?
> thanks

not related to shopfloor. 
This is the standard way of configuring records by env using server-env params.
"Record Name" is the api key record.
In production can be "very-very-secret-prod-key" and on integration "another-one-to-not-mess-up-with-access-rights".
You don't need it for testing shopfloor.

**Comment by guewen** [comment]
And the configuration file is optional, it's an option to have different keys per environment, which is advised anyway, but to start you can create keys in the UI.
