### ISSUE TITLE
try use auth_api key but have error using shopfloor_mobile

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/wms#136]
![auth_api_key](https://user-images.githubusercontent.com/13952131/105181904-afbcb280-5b2c-11eb-81e4-47d12f6367e2.png)
when I push the LOGIN button 
![shopfloor_mobile2](https://user-images.githubusercontent.com/13952131/105182477-5b660280-5b2d-11eb-9aa4-426e35c8331a.png)
this is the console error:
odoo.addons.shopfloor.services.service.ShopfloorServiceDispatchException: dispatch() got an unexpected keyword argument '_id'
can you please document steps to setup shopfloor_mobile?
Thanks

**Comment by simahawk** [comment]
This is not related to shopfloor_mobile but to a refactoring of base_rest here https://github.com/OCA/rest-framework/pull/71
You were so unlucky to start testing between it got merged and the patch done here https://github.com/OCA/wms/pull/133 :sweat_smile: 
Can you update you version and try again?
