### ISSUE TITLE
Field `profile_id` does not exist

### ISSUE THREAD

**Issue by poiswe** [OCA/wms#143]
Hi, i'm getting the following error installing Shopfloor (13.0.2.1.0) in an empty (new/fresh) database. Is there a fast work-around for now?

```
ValueError: <class 'odoo.tools.convert.ParseError'>: "Error while validating view

Field `profile_id` does not exist

Error context:
View `shopfloor menu tree`
[view_id: 1194, xml_id: n/a, model: shopfloor.menu, parent_id: n/a]
```

**Comment by guewen** [comment]
Hi, I just installed the module in a new database without issue, and the `profile_id` field is defined here: https://github.com/OCA/wms/blob/75411c8b023d55878ee04f6c17890ff643670553/shopfloor/models/shopfloor_menu.py#L30-L32
Are you sure you have no local changes in your wms repository?

**Comment by poiswe** [comment]
Hi, I have no changes locally. I tried to install an earlier commit and it works fine. The problem might be that i started the database with no demo data. I'll investigate some more.

**Comment by poiswe** [comment]
> Hi, I just installed the module in a new database without issue, and the `profile_id` field is defined here:
> 
> https://github.com/OCA/wms/blob/75411c8b023d55878ee04f6c17890ff643670553/shopfloor/models/shopfloor_menu.py#L30-L32
> 
> 
> Are you sure you have no local changes in your wms repository?

I'm truly perplexed by this issue, changing the model (shopfloor.menu) property as below and in the corresponding model (shopfloor.profile) and in the view everything seems to work properly.

`shopfloor_profile_id = fields.Many2one(
        comodel_name='shopfloor.profile',
        string='Profile',
        help='Visible on this profile only')`

Could there be some kind of inheritance issue somewhere?

**Comment by simahawk** [comment]
@poiswe none of us has this issue (and we install this module many times for testing).
Do you still have problems?
If yes, please try w/ a fresh checkout of this repo and install it from scratch.

**Comment by poiswe** [comment]
Forgot to close this. In the end it was probably due to a mismatch between the shopfloor_base and shopfloor module or due to the fact that shopfloor_base was not installed. A lot of refactoring has been done since the issue and things seem to work real nice.

@simahawk I've started prototyping a reception-app in Ionic, are there plans to wrap the reception-screen logic as a rest-service?
