### ISSUE TITLE
stock_storage_type: putaway strategy "do not mix" should give priority to location that already contains the product (the one with the less qty)

### ISSUE THREAD

**Issue by lmignon** [OCA/wms#168]
As stated [here](https://github.com/OCA/wms/pull/132#pullrequestreview-571363775) it would be nice to improve the put away strategy for 'do not mix product" to give priority to location that already contains the product.

A solution could be to reorder the list of valid stock locations into the the method [`_select_final_valid_putaway_locations`](https://github.com/OCA/wms/blob/13.0/stock_storage_type/models/stock_location.py#L377). This would require to modify the method signature to pass at least the package_storage_type..

something like this

```python

def _select_final_valid_putaway_locations(
    self, package_storage_type, quants, products, limit=None
):
    locations = self
    if package_storage_type.do_not_mix_products:
        # give priority to the location that already contains the product, the one with the less qty first
        locations = locations.sorted(lambda l:sum(l.mapped('quant_ids.qty')) or 99999)
    return locations[:limit]
``` 

My main concern here is that we break the original order but do we agree that's the expected result in this specific case?

**Comment by lmignon** [comment]
`_select_final_valid_putaway_locations` is maybe not the right place and the reorder should probably be done just before the call to `_select_final_valid_putaway_locations` into [`select_allowed_locations`](https://github.com/OCA/wms/blob/13.0/stock_storage_type/models/stock_location.py#L441)

```python
def select_allowed_locations(
    self, package_storage_type, quants, products, limit=None
):
    ...
    valid_locations = self.browse(
            id_ for id_ in self.ids if id_ in valid_location_ids
        )
    if package_storage_type.do_not_mix_products:
        def sorter(loc):
            total = sum(loc.mapped('quant_ids.qty'))
            return (total is None, total)
        valid_locations = valid_locations.sorted(sorter)
    valid_locations = valid_locations._select_final_valid_putaway_locations(
        limit=limit
    )
    ...

```

**Comment by lmignon** [comment]
The more I dig into the code, the more this issue seems tricky to put in place in an efficient way. The number of valid locations found could be huge, that means that using the orm to compute the qty of products into the locations could introduce performance issue. Moreover, the `do_not_mix_products` is not defined on `stock.package.storage.type` but on `stock.location.storage.type`. IOW, into the list of valid locations, some could be linked to a location storage type with the restriction do_not_mix_product but not all...

**Comment by jbaudoux** [comment]
> Moreover, the `do_not_mix_products` is not defined on `stock.package.storage.type` but on `stock.location.storage.type`. IOW, into the list of valid locations, some could be linked to a location storage type with the restriction do_not_mix_product but not all...

The strategy is defined on the location. You can have a strategy "do not mix" for the pickable stock and another strategy "empty" for the over-stock. However, this will apply for distinct hierarchy of locations, i.e. WH/Stock vs WH/Over-stock and is configured as 2 separate lines in the putaway sequence of the package storage type. Then maybe it would make sense to define the "Allowed locations storage types" for each line of the sequence and they must all share the same strategy.
