### ISSUE TITLE
[QUESTION] stock_dynamic_routing: push rules

### ISSUE THREAD

**Issue by AdriaGForgeFlow** [OCA/wms#34]
Hi,

I have followed the testing steps described here #31 and I have a question regarding the section _Steps to try the Push Routing Transfer_. 

When I create the Purchase Order and confirm it I, indeed, get two pickings as expected but when I validate the first one (using the Validate button) the stock move line is created with the wrong destination location as you can see in the image:

![image](https://user-images.githubusercontent.com/44768500/86356569-be18af00-bc6c-11ea-8014-2f3fa2259805.png)

Instead of Bay A/ Bin 1 it should go to the Handover location. This is because in the action_assign, upon creating the stock move line Odoo is checking for putaway strategies in the destination location of the move (Handover) and it's finding the one that was defined previously in Stock:

* "[DESK0004] Customizable Desk (Aluminium, Black)" from WH/Stock to location "WH/Stock/Highbay/Bay A/Bin 1"

Only reason I find for this to be this way is that it is intended to be like this and the move line must be created manually specifying the destination location. Is that the case?

Thanks in advance.

**Comment by guewen** [comment]
I think the demo data is wrong. The Highbay and Handover should not be below Stock, or the putaway rule should not include everything below Stock, because obviously, as soon as we put something in the handover, it will be put-away in the location defined by the rule... :/

**Comment by jgrandguillaume** [comment]
As we discus this on phone, I close it.
