### ISSUE TITLE
stock_available_to_promise_release - Support multiple warehouses

### ISSUE THREAD

**Issue by mt-software-de** [OCA/wms#397]
Wrong Quantities if multiple warehouses

https://github.com/OCA/wms/blob/2d1cc835a486b4fbda226b4a94b0adc718c7f35f/stock_available_to_promise_release/models/stock_move.py#L174

The method _ordered_available_to_promise_locations returns the view locations of all warehouses.
This method is also used to get the available qty to promise see here:
https://github.com/OCA/wms/blob/2d1cc835a486b4fbda226b4a94b0adc718c7f35f/stock_available_to_promise_release/models/stock_move.py#L189
until line 
https://github.com/OCA/wms/blob/2d1cc835a486b4fbda226b4a94b0adc718c7f35f/stock_available_to_promise_release/models/stock_move.py#L209

There is a problem if we have two different warehouses which are completely independent from each other, than the qty of all warehouses are computed and this is not correct. We should only use the locations of the moves warehouse child locations.

**Comment by Walia8416** [comment]
Please assign this issue to me for HacktoberFest 2022

**Comment by mt-software-de** [comment]
@jbaudoux do you see a problem here too?
The problem would be if we have moves with different warehouses in line https://github.com/OCA/wms/blob/2d1cc835a486b4fbda226b4a94b0adc718c7f35f/stock_available_to_promise_release/models/stock_move.py#L175

**Comment by jbaudoux** [comment]
Yes, it's an actual limitation. Multiple warehouses are not yet supported, it's in the roadmap and a PR to improve this should land soon or later
