### ISSUE TITLE
Function declared as capable of handling request of type 'http' but called with a request of type 'json'

### ISSUE THREAD

**Issue by aixi88** [OCA/wms#414]
## Module
shopfloor_example 14.0

## Describe the bug
shopfloor/app/demo_user/#/login
werkzeug.exceptions.BadRequest: 400 Bad Request: <function post_authenticate at 0x7f9492283b70>, /session/auth/login: Function declared as capable of handling request of type 'http' but called with a request of type 'json'
![Screenshot_2022-05-18 Shopfloor Demo (user auth)](https://user-images.githubusercontent.com/9400678/168936199-3ef0529f-2767-4baa-831f-63ec1c0a0adc.png)

**Comment by simahawk** [comment]
I cannot replicate this on runboat. You can try this on http://oca-wms-14-0-e633705a7961.runboat.odoo-community.org/shopfloor/app/demo_user/ (user: demo/demo)
