### ISSUE TITLE
[BUG] shopfloor_ui_tests filename too long

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/wms#429]
Using Windows if I try to clone this repo I get:
error: unable to create file shopfloor_ui_tests/cypress/screenshots/shopfloor_mobile_base_auth_api_key/test_authentication_apikey.js/Test to make sure that the user can log in and log out -- Log in to the Shopfloor app -- Preparation tests -- Checks that the request to user_config fails (user is not authenticated) (failed).png: Filename too long

@JuMiSanAr Please could you check this?

**Comment by emagdalenaC2i** [comment]
ping @simahawk

**Comment by JuMiSanAr** [comment]
Hello @emagdalenaC2i,

Please note that we haven't encountered any similar issues on our side, as this seems to be Cypress-related.

Could you please check the Cypress documentation regarding screenshots?
https://docs.cypress.io/api/commands/screenshot#Get-screenshot-info-from-the-onAfterScreenshot-callback:~:text=Notes-,Naming%20conventions,-Screenshot%20naming%20follows

According to it, your screenshot name should end after **_apikey.js..

**Comment by poiswe** [comment]
Workaround on Windows:
git config --system core.longpaths true
