### ISSUE TITLE
Backport shopfloor to v12

### ISSUE THREAD

**Issue by mileo** [OCA/wms#44]
Hi,

I start to working at the backport of shopfloor modules to version 12.0.  

https://github.com/kmee/wms/tree/12.0-mig-shopfloor

I didn't find anybody working in this backport yet... if any one is working on it I would like to help. 

I try to do a **git am**:
`git format-patch --keep-subject --stdout kmee/12.0..origin/13.0-shopfloor -- shopfloor | git am -3 --keep --ignore-whitespace`

But i came across many conflicts... I was wondering if it would be a good time to diverge from the branch of @simahawk. So I thought about keeping in sync with PR (https://github.com/OCA/wms/pull/25) to avoid unnecessary rebases. And then when the merge is done, i will create the appropriate PRs for the backport for v12. 

If anyone knows a better approach, please let me know.

Todo:
- [ ] https://github.com/OCA/product-attribute/pull/593
- [ ] https://github.com/OCA/stock-logistics-workflow/pull/590
- [ ] https://github.com/OCA/stock-logistics-workflow/pull/585

**Comment by simahawk** [comment]
@mileo sorry for the late reply. Super busy w/ the project were this app is used.
Actually we are still improving and fixing tons of things. We just went live w/ it and even more changes will come. 

Regarding the approach for conflicts, which conflicts had you faced?

**Comment by mileo** [comment]
Hello Guys.

I don't have time to work on this backport anymore.

If any one wants to continue working on it, please check this WIP PR: https://github.com/OCA/wms/pull/45
