### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by Change2improve** [OCA/wms#468]
As preiously mentioned in #429 there are filenames too long that cause issues in Windows

$ git checkout 15.0
error: cannot stat '**shopfloor_ui_tests/cypress/screenshots/shopfloor_mobile_base_auth_api_key/test_authentication_apikey.js/Test to make sure that the user can log in and log out -- Log in to the Shopfloor app -- Preparation tests -- Checks that the request to user_config fails (user is not authenticated) (failed).png**': Filename too long
error: The following untracked working tree files would be overwritten by checkout:
        .copier-answers.yml
        .editorconfig
        .eslintrc.yml
        .flake8
        .github/workflows/pre-commit.yml
        .github/workflows/stale.yml
        .github/workflows/test.yml
        .gitignore
        .isort.cfg
        .pre-commit-config.yaml
        .prettierrc.yml
        .pylintrc
        .pylintrc-mandatory
        LICENSE
        README.md
        setup/.setuptools-odoo-make-default-ignore
        setup/README

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by poiswe** [comment]
As a workaround set longpaths….
git config --system core.longpaths true
