### ISSUE TITLE
Shopfloor: any plans to migrate to V15? 

### ISSUE THREAD

**Issue by FreezeS** [OCA/wms#490]
Hi guys,

Is there a plan to migrate shopfloor to V15?
Or was it moved to another repository?

**Comment by simahawk** [comment]
Hello,

If you look at PRs for v15 you'll see quite a lot of them https://github.com/OCA/wms/pulls?q=is%3Apr+is%3Aopen+base%3A15.0

On our side (Camptocamp) we haven't started yet working on v15, for lack of time and lack of projs.
We still have to go through the PRs above to do some reviews.

Yet, you could help with reviews and/or functional tests :wink:
