### ISSUE TITLE
Please share more details on how to setup the project locally and run it locally

### ISSUE THREAD

**Issue by sumanghosh12** [OCA/wms#54]
Please share more details on how to setup the project locally and run it locally

**Comment by sumanghosh12** [comment]
Can anyone please hele me setting up the application locally to understand the project and help with my contribution?

**Comment by sumanghosh12** [comment]
@jgrandguillaume Can you please help.

**Comment by simahawk** [comment]
@sumanghosh12 what are you talking about specifically? Running Odoo? Running WMS addons?

**Comment by sumanghosh12** [comment]
@simahawk - Thank you for your reply. I want to build the code locally and run WMS locally. 
I need some help setting up the project locally. Any help would be highly appreciable. Thanks in advance.

**Comment by simahawk** [comment]
@sumanghosh12 OCA/wms is not an app. This repo contains a set of modules that improve WMS on top of Odoo.
You first setup Odoo, add this repo to the available addons and then you should install the modules that you want and test in Odoo.
If you are not familiar with this, you should start from here https://www.odoo.com/documentation.
