### ISSUE TITLE
[REQ] shopfloor_mobile and barcode scanning with mobile phone

### ISSUE THREAD

**Issue by joosuavip** [OCA/wms#69]
Hello,

I've been testing out the wms-modules and I'm very impressed with the features I've found. Now I've been testing shopfloor_mobile and just noticed a handy feature that currently seems to be missing: 

barcode scanning with a mobile phone. 

Currently it seems scanning a barcode in the app needs to happen with a device with an integrated barcode scanner or a bluetooth scanner. Many (web)applications provide an UI with the possibility to scan a barcode using the camera of the phone, which would be a nice feature for the shopfloor_mobile-app. This would make using and testing the app easier and more cost-efficient since it wouldn't require a user to get a barcode scanner-enabled device. I'm interested in using this app in my company's warehouse and right now we're using mobile phones to process Delivery Orders. It would be a big help if we could continue to use the same devices with shopfloor_mobile also. It would be great if you'd consider adding this as a feature to the app.

I'm sorry if this isn't the right place to post requests, please move this to a better place or give advice for the right way to request features.

**Comment by simahawk** [comment]
@joosuavip thanks for your feedback. Scanning w/out scan device: seems to be an handy feature. 
At the moment there's no plan (as far as I know) to add it. You could work on it or sponsor it.
