### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by ritco** [OCA/wms#71]
We're using the shopfloor app and need to re-enter the API key every day or sometimes multiple times a day. Is this normal behaviour?

**Comment by simahawk** [comment]
@ritco yes. Most of the time (at least in our case) operators always use the same device.
One option we thought about was to be able to scan the key from a barcode. That would be very fast.
Do you have any other proposal? 
In any case, feel free to work on it or to sponsor it. Contributes are always welcome :wink:
