### ISSUE TITLE
[14.0] Reception Mobile: You need to supply a Lot/Serial Number for product 

### ISSUE THREAD

**Issue by hitrosol** [OCA/wms#728]
## Module
shopfloor_reception_mobile and other related modules.

## Describe the bug

UserError(_('You need to supply a Lot/Serial Number for product: \n - ') +
odoo.exceptions.UserError: You need to supply a Lot/Serial Number for product:  - [FURN_7777] Office Chair,
eventhough i have input the Lot/Serial Number for product.

## To Reproduce
V14. I try this on runboat :
using link:
http://oca-wms-14-0-a8ddb01413fa.runboat.odoo-community.org/web#action=139&model=shopfloor.app&view_type=list&cids=&menu_id=110
using Shopfloor Demo (user auth), username and pass : demo, demo.

1. Change the traceability of [FURN_7777] Office Chair to be tracking by Lot.
2. Try to receive WH/IN/00002 where there are 35 unit of that product.
3. Scan the product
4.  Input Lot
5. Input Expired date
6. Input Qty
7. Process without Pack
8. Set Destination Location
9. Mark As Done
10. Confirm
11.  The error message appear:  400 Bad Request, You need to supply a Lot/Serial Number for product - [FURN_7777] Office Chair.

**Expected behavior**
User can input new Lot / Serial number in shopfloor mobile smoothly.

**Additional context**
Running it on runboat and local

**Comment by hitrosol** [comment]
is this a valid bug, or do i miss some configuration / steps ?

**Comment by simahawk** [comment]
@mmequignon could you pls have a look here?

**Comment by hitrosol** [comment]
I record my screen for that error as follow:
https://www.youtube.com/watch?v=5YT8th3A3k4
Also the runboat link : 
http://oca-wms-14-0-b5737bee9fa2.runboat.odoo-community.org/web#action=327&model=stock.picking.type&view_type=list&cids=&menu_id=193


Is there any steps I missed ?

**Comment by hitrosol** [comment]
I found it's working now, maybe I missed something previously.
Good Job....
