### ISSUE TITLE
Split of Shopfloor

### ISSUE THREAD

**Issue by bguillot** [OCA/wms#76]
Hello, 

I want to use shopfloor in V12, so I planned to backport it.

I will not use all the dependencies, for instance the storage types, the manufacturer.

So I propose to split shopfloor  in V13 to reduce the dependencies of the module shopfloor (to avoid backport of modules that I will not use at all and maybe no one will because its in V12)

Moreover, I discussed that with @simahawk, and he proposed also to create a module shopfloor_base and put there all the base stuff without the scenarios, it makes sense if you want to use shopfloor but with other scenarios.

If you have some comments or advice, they are welcomed.

I will make a PR regarding that.

Thanks !

**Comment by bguillot** [comment]
@hparfr @sebastienbeau @simahawk @guewen 

This can interest you ! :)

**Comment by hparfr** [comment]
I think in my projects, - if possible- I will not use theses direct dependencies of shopfloor: 
```py
 "stock_quant_package_dimension",
 "stock_quant_package_product_packaging",
 "product_manufacturer",
 "stock_storage_type",
 "product_packaging_type",
```

**Comment by simahawk** [comment]
@hparfr @bguillot any progress on this?

**Comment by simahawk** [comment]
To split as well:

`split_other_move_lines` + `extract_and_action_done`

See https://github.com/OCA/stock-logistics-warehouse/pull/1021/files#diff-a219cfbd181e803b6c8f7df2986886a73c96fac489a57ebf671c4eae43f0a459R14

**Comment by hparfr** [comment]
> @hparfr @bguillot any progress on this?

Not that much, for the moment we port all the dependencies  :see_no_evil:

**Comment by lmignon** [comment]
@hparfr We are also very interested by the split of shopfloor... We also plan to use shopfloor_base once created on odoo 10 for our new scenario to develop for one of our client.

**Comment by simahawk** [comment]
split happened already on v13 and v14.
