### ISSUE TITLE
[RFC] Shopfloor: prevent user login on two devices at the same time

### ISSUE THREAD

**Issue by simahawk** [OCA/wms#87]
ATM there's no shared notion of "logged in user" between Odoo and the app.

Probably we should have something similar to POS and have a `shopfloor.session`.

It could work like:

1. login -> I create a session (which will store the IP of the device as well, user, etc)
2. when try to login from another device -> check if session is active and from a different IP -> ask to take over -> invalidate former session
3. sessions will have a TTL and will be wiped after this time automatically
4. In theory on every request we should check if the session is still valid otherwise if you try to use a device which was logged in and left on any screen but login will lead to the same problem (could come from an HTTP header) -> this might add overhead
5. as an alternative to pt 4 we could use push notifications to notify the device the session has been overtaken and logout

@guewen @sebalix @sebastienbeau @hparfr @bguillot what do you think? Any better/easier/more flexible/more secure/pick-your-motivation option?

**Comment by hparfr** [comment]
Hi,

What is the use case ?  Users impersonating colleagues ?

**Comment by jgrandguillaume** [comment]
I propose to close this one for now. As it is call are always sending all context, even if more than one person use the same login it should not be a problem.
