### ISSUE TITLE
Backport to 10.0

### ISSUE THREAD

**Issue by lmignon** [OCA/wms#92]
Hi,

I'm backporting some wms addons to 10.0. Can you create the 10.0 branch. I already prepared the branch here https://github.com/acsone/wms/tree/10.0
Once the branch will be created I'll create a PR with the backport of `stock_storage_type` https://github.com/acsone/wms/tree/10.0-backport-stock-storage-type

Regards

**Comment by jgrandguillaume** [comment]
All done

**Comment by lmignon** [comment]
Thank you @jgrandguillaume
